# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftTut' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftTut
  pod 'SnapKit', '~> 3.0'
  pod 'RxSwift', '~> 3.0'
  pod 'RxCocoa'
  pod 'Moya', '8.0.0-beta.4'
  pod 'Moya-ModelMapper', '4.0.0-beta.3'
  pod 'Moya-ModelMapper/RxSwift', '4.0.0-beta.3'
  pod 'RxOptional'
end
